In [43]:
import pandas as pd

In [44]:
 df = pd.read_csv('loan_train.csv')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [13]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [15]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [16]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [17]:
df.shape

(614, 13)

In [63]:
df.apply(lambda x :sum(x.isnull()), axis=0)

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [47]:
df['LoanAmount'].fillna(df['LoanAmount'].mean(),inplace=True)

C:\Users\Pc\AppData\Local\Temp\ipykernel_20340\2424903021.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['LoanAmount'].fillna(df['LoanAmount'].mean(),inplace=True)

In [29]:
print(x)

None

In [48]:
df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mean(),inplace=True)

C:\Users\Pc\AppData\Local\Temp\ipykernel_20340\2500419422.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mean(),inplace=True)

In [49]:
df['Credit_History'].fillna(df['Credit_History'].count(),inplace=True)

C:\Users\Pc\AppData\Local\Temp\ipykernel_20340\2004430335.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Credit_History'].fillna(df['Credit_History'].count(),inplace=True)

In [51]:
df['Dependents'].value_counts()

Dependents
0     345
1     102
2     101
3+     51
Name: count, dtype: int64

In [52]:
df['Dependents'].fillna('0',inplace=True)

C:\Users\Pc\AppData\Local\Temp\ipykernel_20340\127408539.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Dependents'].fillna('0',inplace=True)

In [54]:
df['Gender'].value_counts()

Gender
Male      489
Female    112
Name: count, dtype: int64

In [55]:
df['Gender'].fillna('Male',inplace=True)

C:\Users\Pc\AppData\Local\Temp\ipykernel_20340\2906177709.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna('Male',inplace=True)

In [57]:
df['Gender'].value_counts()

Gender
Male      502
Female    112
Name: count, dtype: int64

In [58]:
df['Married'].value_counts()

Married
Yes    398
No     213
Name: count, dtype: int64

In [59]:
df['Married'].fillna('Yes',inplace=True)

C:\Users\Pc\AppData\Local\Temp\ipykernel_20340\589474670.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Married'].fillna('Yes',inplace=True)

In [61]:
df['Self_Employed'].value_counts()

Self_Employed
No     500
Yes     82
Name: count, dtype: int64

In [62]:
df['Self_Employed'].fillna('No',inplace=True)

C:\Users\Pc\AppData\Local\Temp\ipykernel_20340\4289460126.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Self_Employed'].fillna('No',inplace=True)

In [69]:
df.duplicated().value_counts()

False    614
Name: count, dtype: int64

In [66]:
df.shape

(614, 13)

In [70]:
df.drop('Loan_ID',axis=1,inplace=True)

In [71]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,146.412162,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,2900,0.0,71.000000,360.0,1.0,Rural,Y
610,Male,Yes,3+,Graduate,No,4106,0.0,40.000000,180.0,1.0,Rural,Y
611,Male,Yes,1,Graduate,No,8072,240.0,253.000000,360.0,1.0,Urban,Y
612,Male,Yes,2,Graduate,No,7583,0.0,187.000000,360.0,1.0,Urban,Y
613,Female,No,0,Graduate,Yes,4583,0.0,133.000000,360.0,0.0,Semiurban,N

In [76]:
from sklearn.preprocessing import LabelEncoder

In [77]:
le = LabelEncoder()

In [84]:
df['Gender'] = le.fit_transform(df['Gender'])

In [89]:
df.drop('Gender_encoded',axis=1,inplace=True)

In [85]:
df['Gender_encoded']

0      1
1      1
2      1
3      1
4      1
      ..
609    0
610    1
611    1
612    1
613    0
Name: Gender, Length: 614, dtype: int64

In [90]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1,No,0,Graduate,No,5849,0.0,146.412162,360.0,1.0,Urban,Y
1,1,Yes,1,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural,N
2,1,Yes,0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban,Y
3,1,Yes,0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban,Y
4,1,No,0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,No,0,Graduate,No,2900,0.0,71.000000,360.0,1.0,Rural,Y
610,1,Yes,3+,Graduate,No,4106,0.0,40.000000,180.0,1.0,Rural,Y
611,1,Yes,1,Graduate,No,8072,240.0,253.000000,360.0,1.0,Urban,Y
612,1,Yes,2,Graduate,No,7583,0.0,187.000000,360.0,1.0,Urban,Y
613,0,No,0,Graduate,Yes,4583,0.0,133.000000,360.0,0.0,Semiurban,N

In [91]:
df['Married'] = le.fit_transform(df['Married'])

In [92]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1,0,0,Graduate,No,5849,0.0,146.412162,360.0,1.0,Urban,Y
1,1,1,1,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural,N
2,1,1,0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban,Y
3,1,1,0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban,Y
4,1,0,0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,Graduate,No,2900,0.0,71.000000,360.0,1.0,Rural,Y
610,1,1,3+,Graduate,No,4106,0.0,40.000000,180.0,1.0,Rural,Y
611,1,1,1,Graduate,No,8072,240.0,253.000000,360.0,1.0,Urban,Y
612,1,1,2,Graduate,No,7583,0.0,187.000000,360.0,1.0,Urban,Y
613,0,0,0,Graduate,Yes,4583,0.0,133.000000,360.0,0.0,Semiurban,N

In [93]:
cols = df.select_dtypes(include=['object']).columns

In [95]:
for col in cols:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])

In [4]:
df

NameError: name 'df' is not defined

In [3]:
df.duplicated()

NameError: name 'df' is not defined